"""
CEO Briefing Generator - Weekly business audit and report

Generates comprehensive weekly briefing including:
- Revenue summary
- Completed tasks
- Bottlenecks
- Proactive suggestions
- Upcoming deadlines
"""

import sys
import logging
import json
from pathlib import Path
from datetime import datetime, timedelta

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)


class CEOBriefingGenerator:
    """Generate weekly CEO briefings."""
    
    def __init__(self, vault_path: str):
        """
        Initialize briefing generator.
        
        Args:
            vault_path: Path to Obsidian vault
        """
        self.vault_path = Path(vault_path)
        self.done = self.vault_path / 'Done'
        self.logs = self.vault_path / 'Logs'
        self.accounting = self.vault_path / 'Accounting'
        self.briefings = self.vault_path / 'Briefings'
        self.business_goals = self.vault_path / 'Business_Goals.md'
        
        # Ensure directories exist
        for folder in [self.briefings, self.accounting]:
            folder.mkdir(parents=True, exist_ok=True)
        
        self.logger = logging.getLogger(self.__class__.__name__)
    
    def generate_briefing(self) -> Path:
        """
        Generate weekly CEO briefing.
        
        Returns:
            Path to generated briefing file
        """
        self.logger.info('Generating CEO Briefing...')
        
        # Get current week info
        today = datetime.now()
        week_start = today - timedelta(days=today.weekday())
        week_number = today.isocalendar()[1]
        
        # Collect data
        completed_tasks = self._get_completed_tasks()
        revenue_data = self._get_revenue_data()
        bottlenecks = self._identify_bottlenecks()
        suggestions = self._generate_suggestions()
        upcoming_deadlines = self._get_upcoming_deadlines()
        
        # Generate briefing content
        content = f'''---
type: ceo_briefing
week: {today.year}-W{week_number}
generated: {datetime.now().isoformat()}
period_start: {week_start.strftime('%Y-%m-%d')}
period_end: {today.strftime('%Y-%m-%d')}
---

# CEO Weekly Briefing

**Week:** {week_number} of {today.year}  
**Period:** {week_start.strftime('%b %d')} - {today.strftime('%b %d, %Y')}  
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## Executive Summary

{self._generate_executive_summary(revenue_data, completed_tasks)}

---

## Revenue Summary

| Metric | Amount |
|--------|--------|
| **This Week** | ${revenue_data['this_week']:,.2f} |
| **Month to Date** | ${revenue_data['mtd']:,.2f} |
| **Monthly Goal** | ${revenue_data['goal']:,.2f} |
| **Progress** | {revenue_data['progress']:.1f}% |

### Revenue Trend

{self._generate_revenue_chart(revenue_data)}

---

## Completed Tasks

Total completed this week: **{len(completed_tasks)}**

'''
        
        # Add completed tasks
        if completed_tasks:
            for task in completed_tasks[:10]:  # Show top 10
                content += f'- [x] {task}\n'
            if len(completed_tasks) > 10:
                content += f'- ... and {len(completed_tasks) - 10} more\n'
        else:
            content += '_No tasks completed this week_\n'
        
        content += f'''
---

## Bottlenecks Identified

{bottlenecks}

---

## Proactive Suggestions

{suggestions}

---

## Upcoming Deadlines

{upcoming_deadlines}

---

## Key Metrics

| Metric | Target | Current | Status |
|--------|--------|---------|--------|
| Client Response Time | < 24 hours | {self._get_avg_response_time()} | {"✅" if self._get_avg_response_time() < 24 else "⚠️"} |
| Invoice Payment Rate | > 90% | {self._get_payment_rate()}% | {"✅" if self._get_payment_rate() > 90 else "⚠️"} |
| Software Costs | < $500/month | ${self._get_software_costs()} | {"✅" if self._get_software_costs() < 500 else "⚠️"} |

---

## Action Items for Next Week

1. [ ] Review and address bottlenecks
2. [ ] Implement proactive suggestions
3. [ ] Follow up on pending invoices
4. [ ] Prepare for upcoming deadlines

---

*Briefing generated by AI Employee v1.0 (Gold Tier)*
'''
        
        # Save briefing
        filename = f'{today.year}-W{week_number}_CEO_Briefing.md'
        filepath = self.briefings / filename
        filepath.write_text(content, encoding='utf-8')
        
        self.logger.info(f'Briefing saved to: {filepath}')
        
        # Update Dashboard
        self._update_dashboard(filepath)
        
        return filepath
    
    def _get_completed_tasks(self) -> list:
        """Get completed tasks from Done folder."""
        tasks = []
        
        if not self.done.exists():
            return tasks
        
        # Get files from this week
        week_start = datetime.now() - timedelta(days=7)
        
        for file in self.done.glob('*.md'):
            try:
                mtime = datetime.fromtimestamp(file.stat().st_mtime)
                if mtime > week_start:
                    # Extract task from filename
                    task_name = file.stem.replace('_', ' ').replace('-', ' ')
                    tasks.append(task_name)
            except:
                pass
        
        return tasks
    
    def _get_revenue_data(self) -> dict:
        """Get revenue data from accounting logs."""
        # Mock data - in production would read from Odoo/Xero
        return {
            'this_week': 2450.00,
            'mtd': 4500.00,
            'goal': 10000.00,
            'progress': 45.0,
            'daily': [350, 500, 420, 680, 500]  # Last 5 days
        }
    
    def _generate_executive_summary(self, revenue: dict, tasks: list) -> str:
        """Generate executive summary."""
        progress = revenue['progress']
        
        if progress >= 80:
            summary = f"**Excellent week!** Revenue at {progress:.0f}% of monthly goal with {len(tasks)} tasks completed."
        elif progress >= 50:
            summary = f"**Good progress.** Revenue at {progress:.0f}% of monthly goal. {len(tasks)} tasks completed this week."
        else:
            summary = f"**Needs attention.** Revenue at {progress:.0f}% of monthly goal. Consider accelerating business development."
        
        return summary
    
    def _generate_revenue_chart(self, revenue: dict) -> str:
        """Generate ASCII revenue chart."""
        daily = revenue.get('daily', [])
        if not daily:
            return '_No daily data available_'
        
        max_val = max(daily) if daily else 1
        chart = ''
        for i, val in enumerate(daily):
            bar_len = int((val / max_val) * 20)
            day_name = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'][i] if i < 5 else f'Day {i+1}'
            chart += f'  {day_name}: {"█" * bar_len} ${val:.0f}\n'
        
        return chart
    
    def _identify_bottlenecks(self) -> str:
        """Identify bottlenecks from logs."""
        bottlenecks = []
        
        # Check for slow response times
        avg_response = self._get_avg_response_time()
        if avg_response > 24:
            bottlenecks.append(f'- ⚠️ **Slow Response Time**: Average {avg_response:.1f} hours (target: < 24h)')
        
        # Check for pending invoices
        pending_count = 3  # Mock data
        if pending_count > 0:
            bottlenecks.append(f'- 💰 **Pending Invoices**: {pending_count} invoices awaiting payment')
        
        # Check for unprocessed items
        needs_action = self.vault_path / 'Needs_Action'
        if needs_action.exists():
            pending = len(list(needs_action.glob('*.md')))
            if pending > 5:
                bottlenecks.append(f'- 📋 **Backlog**: {pending} items pending in Needs_Action')
        
        if not bottlenecks:
            return '_No bottlenecks identified this week ✓_'
        
        return '\n'.join(bottlenecks)
    
    def _generate_suggestions(self) -> str:
        """Generate proactive suggestions."""
        suggestions = []
        
        # Check for unused subscriptions
        suggestions.append('- 💡 **Cost Optimization**: Review software subscriptions for unused services')
        
        # Check for follow-up opportunities
        suggestions.append('- 📧 **Follow-ups**: 3 client proposals sent last week - follow up this week')
        
        # Check for automation opportunities
        suggestions.append('- 🤖 **Automation**: Consider automating weekly report generation')
        
        return '\n'.join(suggestions)
    
    def _get_upcoming_deadlines(self) -> str:
        """Get upcoming deadlines."""
        deadlines = [
            {'task': 'Project Alpha milestone', 'date': datetime.now() + timedelta(days=5)},
            {'task': 'Monthly tax filing', 'date': datetime.now() + timedelta(days=15)},
        ]
        
        output = ''
        for dl in deadlines:
            days_left = (dl['date'] - datetime.now()).days
            output += f'- 📅 **{dl["task"]}**: {dl["date"].strftime("%b %d")} ({days_left} days left)\n'
        
        return output
    
    def _get_avg_response_time(self) -> float:
        """Get average response time in hours."""
        return 12.5  # Mock data
    
    def _get_payment_rate(self) -> float:
        """Get invoice payment rate percentage."""
        return 92.5  # Mock data
    
    def _get_software_costs(self) -> float:
        """Get monthly software costs."""
        return 350.00  # Mock data
    
    def _update_dashboard(self, briefing_path: Path):
        """Update dashboard with briefing info."""
        dashboard = self.vault_path / 'Dashboard.md'
        
        if not dashboard.exists():
            return
        
        content = dashboard.read_text(encoding='utf-8')
        
        # Add briefing link to recent activity
        briefing_link = f'- [{briefing_path.name}]({briefing_path})'
        
        if '## CEO Briefings' in content:
            # Add to briefings section
            content = content.replace(
                '## CEO Briefings',
                f'## CEO Briefings\n\n{briefing_link}'
            )
        
        dashboard.write_text(content, encoding='utf-8')
        self.logger.info('Dashboard updated')


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description='CEO Briefing Generator')
    parser.add_argument('vault_path', nargs='?', default='../AI_Employee_Vault',
                       help='Path to Obsidian vault')
    parser.add_argument('--once', action='store_true',
                       help='Generate once and exit')
    parser.add_argument('--weekly', action='store_true',
                       help='Generate weekly briefing')
    
    args = parser.parse_args()
    
    vault_path = Path(args.vault_path)
    
    if not vault_path.exists():
        print(f'Error: Vault not found: {vault_path}')
        sys.exit(1)
    
    generator = CEOBriefingGenerator(str(vault_path))
    
    if args.once or args.weekly:
        briefing = generator.generate_briefing()
        print(f'Briefing generated: {briefing}')
    else:
        print('CEO Briefing Generator')
        print('\nCommands:')
        print('  --once    Generate briefing now')
        print('  --weekly  Generate weekly briefing (for scheduler)')


if __name__ == '__main__':
    main()
